export const allInstitutes = [
  "Instituto de Artes",
  "Instituto de Biologia",
  "Instituto de Computação",
  "Instituto de Economia",
  "Instituto de Estudos da Linguagem",
  "Instituto de Filosofia e Ciências Humanas",
  "Instituto de Física",
  "Instituto de Geociências",
  "Instituto de Matemática, Estatística e Computação Científica",
  "Instituto de Química",
  "Faculdade de Ciências Aplicadas",
  "Faculdade de Ciências Farmacêuticas",
  "Faculdade de Enfermagem",
  "Faculdade de Eng. de Alimentos",
  "Faculdade de Eng. Agrícola",
  "Faculdade de Eng. Civil, Arquitetura e Urbanismo",
  "Faculdade de Eng. Elétrica e de Computação",
  "Faculdade de Eng. Mecânica",
  "Faculdade de Eng. Química",
  "Faculdade de Ciências Médicas",
  "Faculdade de Educação Física",
  "Faculdade de Odontologia de Piracicaba",
  "Faculdade de Educação",
  "Faculdade de Tecnologia"
]